name: grimoji
description:  A gothic alchemy game for mixing and collecting emojis.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^17.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^8.1.0
  game_levels_scrolling_map: ^0.0.7
  drop_shadow:
  flutter_svg: ^2.0.10
  lottie: ^3.1.2
  uuid: ^4.5.3
  
dependency_overrides:
  xml: ^6.6.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0
  test: ^1.24.3
  flutter_native_splash: ^2.4.7
  path: ^1.9.1
  http: ^1.6.0
  msix: ^3.16.13
  mockito: ^5.6.4
  fake_async: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Eagle Lake
      fonts:
        - asset: assets/fonts/EagleLake-Regular.ttf
    - family: Caudex
      fonts:
        - asset: assets/fonts/Caudex-Regular.ttf

  assets:
    - assets/images/
    - assets/images/map/
    - assets/images/tab/
    - assets/images/level/
    - assets/images/grimoire/
    - assets/emojis/lottie/
    - assets/emojis/svg/
    - assets/lottie/
    - assets/mascot/
    - assets/icons/
    - assets/icons/app/
    - assets/music/
    - assets/sfx/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/2048x2048_bg.png"
  adaptive_icon_background: "#1a1a24"
  adaptive_icon_foreground: "assets/icons/2048x2048_bg.png"

  web:
      generate: true
      image_path: "assets/icons/512x512.png" 
      theme_color: "#1a1a24"

flutter_native_splash:
  color: "#1a1a24" 
  android: true
  ios: true
  image: "assets/icons/splash.png"

  android_12:
    color: "#1a1a24"
    image: "assets/icons/splash.png"

msix_config:
  display_name: Grimoji
  publisher_display_name: Ghetto Coders
  identity_name: GhettoCoders.Grimoji
  publisher: CN=9AD0141A-3599-4A6C-BC62-AFB18E2AF8EC
  logo_path: assets/icons/512x512.png
  capabilities: "internetClient"